[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  SECRETS_SCAN_OMIT_KEYS = "CLOUDINARY_API_KEY,CLOUDINARY_API_SECRET,CLOUDINARY_CLOUD_NAME,CLOUDINARY_UPLOAD_PRESET,CLOUDINARY_URL,DATABASE_URL,NEXT_PUBLIC_BASE_URL,NOTIFY_EMAIL,SEED_ADMIN_EMAIL,SEED_ADMIN_PASSWORD,SMTP_HOST,SMTP_PASS,SMTP_PORT,SMTP_USER,VITE_SUPABASE_ANON_KEY,VITE_SUPABASE_URL"
